version: '3.1'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - "/storage/data/dotnetspider/zk1/data:/data"
      - "/storage/data/dotnetspider/zk1/datalog:/datalog"
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - "/storage/data/dotnetspider/zk2/data:/data"
      - "/storage/data/dotnetspider/zk2/datalog:/datalog"
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - "/storage/data/dotnetspider/zk3/data:/data"
      - "/storage/data/dotnetspider/zk3/datalog:/datalog"
  kafka1:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=100
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/data/dotnetspider/kafka1:/bitnami/kafka
  kafka2:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=101
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9093
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/data/dotnetspider/kafka2:/bitnami/kafka
  kafka3:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=102
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9094
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/data/dotnetspider/kafka3:/bitnami/kafka